baseurl: ""
url: "https://avdheshkushwah.pages.dev"

title: "Avdhesh Kushwah"
description: "Avdhesh Kushwah, Avdhesh Kushwah Gwalior, Avdhesh Kushwah Gadroli, Avdhesh Kushwah Official, Avdhesh Kushwah Website, Avdhesh Kushwah Photos & Videos."
og_image: "/assets/img/ak-logo.png"

plugins:
  - jekyll-sitemap
  - search_generator.rb

include:
  - _plugins
