plugins:
  - jekyll-sitemap
  
baseurl: ""
url: "https://ak-official.pages.dev"

# Default metadata (fallbacks)
title: "Avdhesh Kushwah Official "
description: "Avdhesh Kushwah, Avdhesh Kushwah Gwalior, Avdhesh Kushwah Gadroli, Avdhesh Kushwah Official Website, Avdhesh Kushwah Photos & Videos."
og_image: "/assets/img/ak-logo.png"

sitemap:
  file: "/sitemap.xml"  # Default hi hai
  exclude:  # Agar Koi Page Hide Karna Ho
    - "/secret-page/"
